dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

branches:
  only:
    - master
    - versions/v1
    - versions/v2

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  ng test ngxSkltn --browsers ChromeHeadlessNoSandbox --watch=false
